version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rabbitmq-net

  # openldap:
  #   image: bitnami/openldap:latest
  #   ports:
  #     - 1389:1389
  #     - 1636:1636
  #     - 636:636
  #   environment:
  #     - LDAP_ADMIN_USERNAME=admin
  #     - LDAP_ADMIN_PASSWORD=adminpassword
  #     - LDAP_USERS=user01,customuser
  #     - LDAP_PASSWORDS=password1,custompassword
  #     - LDAP_ROOT=dc=example,dc=org
  #     - LDAP_ADMIN_DN=cn=admin,dc=example,dc=org
  #   volumes:
  #     - openldap_data:/bitnami/openldap
  #     - ./ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
      
networks:
  rabbitmq-net:
    driver: bridge
