spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: tour-route
              uri: http://localhost:8082
              predicates:
                - Path=/tours/**
            - id: tour-route2
              uri: http://localhost:8082
              predicates:
                - Path=/api/tours/**
            - id: packages-route
              uri: http://localhost:8082
              predicates:
                - Path=/packages/**
            - id: tour-rating-route
              uri: http://localhost:8082
              predicates:
                - Path=/ratings/**
            - id: tour-image-route
              uri: http://localhost:8081
              predicates:
                - Path=/images/**
              filters:
                - PrefixPath=/api